---
- name: Ensure dpkg is set up to remove any previous apache
  shell: dpkg --configure -a
  become: yes

- name: Purge the apache webserver
  apt: pkg={{ item }} state=absent purge=yes
  with_items:
    - apache2

- name: Remove any previous apache config
  file: path=/etc/apache2 state=absent
  become: yes

- name: Install the apache webserver
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items:
    - apache2

- name: Install apache modules
  shell: a2enmod {{ item }}
  with_items:
    - proxy
    - proxy_ajp
    - proxy_http
    - rewrite
    - substitute
  become: yes

- name: Copy apache proxy config
  template: src=apache_proxy.conf.j2 dest="/etc/apache2/mods-enabled/proxy.conf"
  become: yes

- name: Copy apache virtualhost config with redirects
  template: src=apache_default_virtualhost.j2 dest="/etc/apache2/sites-enabled/000-default.conf"
  become: yes

- name: Copy apache SSL config with redirects
  when: dryad.is_production
  template: src=apache_ssl_virtualhost.j2 dest="/etc/apache2/sites-enabled/ssl.conf"
  become: yes

- name: Ensure certs directory is present and writable
  when: dryad.is_production
  file: path=/etc/apache2/certs state=directory owner={{ dryad.user }} mode=0755

- name: Get SSL cert main
  when: dryad.is_production
  aws_s3:
    bucket: dryad-backup
    object: apache/2017.datadryad.org.crt
    dest: "/etc/apache2/certs/2017.datadryad.org.crt"
    mode: get
  become: no
  ignore_errors: yes

- name: Get SSL cert CA
  when: dryad.is_production
  aws_s3:
    bucket: dryad-backup
    object: apache/2017.datadryad.org.ca-bundle
    dest: "/etc/apache2/certs/2017.datadryad.org.ca-bundle"
    mode: get
  become: no
  ignore_errors: yes

- name: Get SSL cert key
  when: dryad.is_production
  aws_s3:
    bucket: dryad-backup
    object: apache/2017.datadryad.org.key
    dest: "/etc/apache2/certs/2017.datadryad.org.key"
    mode: get
  become: no
  ignore_errors: yes

- name: Get SSL cert DataONE
  when: dryad.is_production
  aws_s3:
    bucket: dryad-backup
    object: apache/DataONECAChain.crt
    dest: "/etc/apache2/certs/DataONECAChain.crt"
    mode: get
  become: no
  ignore_errors: yes

- name: Create apache convenience directory
  file: path={{ dryad.user_home }}/apache state=directory owner={{ dryad.user }} mode=0755

- name: Create symlink for access to apache config
  file: src=/etc/apache2 dest={{ dryad.user_home }}/apache/conf state=link owner={{ dryad.user }}

- name: Create symlink for access to apache logs
  file: src=/var/log/apache2 dest={{ dryad.user_home }}/apache/log state=link owner={{ dryad.user }}

- name: Install utility script to restart apache
  template: src=apache_restart.sh.j2 dest="{{ dryad.user_home }}/bin/apache_restart.sh" mode=0755
  become: no

- name: Restart apache to pick up the new config settings
  service: name=apache2 state=restarted
  become: yes
