---
- name: Install useful command-line tools
  apt: pkg={{ item }} state=installed update-cache=yes
#  async: 60
#  poll: 60
  with_items:
    - emacs24
    - ack-grep
    - python-pip
    - mailutils

- name: Update awscli
  shell: pip install awscli
  become: no
  
- name: Create hidden dir for AWS
  file: path={{ dryad.user_home }}/.aws state=directory owner={{ dryad.user }} mode=0755
  
- name: Install AWS config file
  template: src=aws_config.j2 dest="{{ dryad.user_home }}/.aws/config" mode=0600 owner={{ dryad.user }}
  remote_user: "{{ dryad.user }}"

- name: Install AWS credentials file
  template: src=aws_credentials.j2 dest="{{ dryad.user_home }}/.aws/credentials" mode=0600 owner={{ dryad.user }}
  remote_user: "{{ dryad.user }}"

- name: Register with AWS OpsWorks on first login
  template: src=aws_opsworks.sh.j2 dest="{{ dryad.user_home }}/.aws/aws_opsworks.sh" mode=0755
  become: no

- name: Clone dryad-utils repo
  git: repo=https://github.com/{{ dryad.github_user }}/dryad-utils.git
       dest="{{ dryad.user_home }}/dryad-utils"
       accept_hostkey=yes
  become: no
